---
- hosts: ngp-redis
  become: True
  tasks: 
  - name: Ensure or set hostname
    hostname: name='{{hostname}}'
  - name: Fix hosts file permissions
    file: path=/etc/hosts mode=0644
  - name: Redis service 1
    service: name='{{p1}}' state=started enabled=yes
  - name: Redis service 2
    service: name='{{p2}}' state=started enabled=yes
   
  

  
  

